[project]
name = 'Tokenized-Community-Childcare-Coordination-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.activity-planning]
path = 'contracts/activity-planning.clar'
clarity_version = 2
epoch = 2.5

[contracts.emergency-contact]
path = 'contracts/emergency-contact.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
